name: keyboard_utils_example
description: Demonstrates how to use the keyboard_utils plugin.
publish_to: 'none'

version: 0.0.1+0.0.1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  keyboard_utils_fork:
    path: ../

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

